-- configure.sql
ALTER SESSION SET CONTAINER = FREEPDB1;

ALTER USER APEX_PUBLIC_USER ACCOUNT UNLOCK;

ALTER SYSTEM SET JOB_QUEUE_PROCESSES = 1000;

ALTER USER sys IDENTIFIED BY Oracle123#apex;

EXIT;